### PR TITLE
Facilitate stateholder creation

### PR DESCRIPTION
**Pull request by rickardlantz**
This PR adds a few classes which aims to facilitate the creation of, and data conversion between [state holder properties](https://developer.android.com/jetpack/compose/state#state-holder-source-of-truth), and data models.

This is done using the class `MutableStateProviderFor` which has utility functions for creating new `MutableState`-objects based on parameters from model classes. Doing so it maintains a record on how to load/save the state-holder data to/from the model classes. See class documentation for more info.

### CODE REVIEW

**Comment by j-nordin** [comment]
I do not really understand the 'MutableStateProviders' and have some questions about them. But now I think I understand how the DI is intended to be used and how it reduces the "prop drilling".

**Comment by j-nordin** [comment]
Now I see I was wrong.. then I also have some questions about the DI.

**Comment by rickardlantz** [comment]
> Now I see I was wrong.. then I also have some questions about the DI.

The assumptions you made in your previous comment are mostly correct! However, I decided to still supply the ViewModel as properties in the end.

This decision was made to allow the navigation host to trigger the updating of data from the server before the navigation is performed, which only happens on the first time you open the screen. I did not manage to find a way to update the state only on the first time the screen was shown from inside the screen composable, as it updated on configuration changes as well.

However, there is nothing stopping us from injecting the ViewModel in the navigation, _and_ inside the Screen composable to reduce the prop-drilling. They should after all get the same instance provided that they request with the same ID.

**Review by axelhertzberg — APPROVED** [review]
Everything is working for me.
I do not fully understand the code, but I understand on how to create new MutableStates in our components, and how we use DI for our viewModels.

**Pull request merged**
