### PR TITLE
Add figma colors and typography, add ordination screen shell as example.

### PR DESCRIPTION
**Pull request by rickardlantz**
This branch adds colors and typography taken from Figma to make the landing page more like the design.

It also adds a wrapper composable which contains the title and navigation buttons the are present on all detail screens. An empty ordination screen with only this shell has been added so that this can be tested.

### CODE REVIEW

**Review by j-nordin — COMMENTED** [review]
Should our screens be contained in a separate package? If so I think this looks good and we should refactor the other screens to also be in the same package!

**Comment by axelhertzberg** [comment]
Got a error when trying to run the application, and i don't understand it. 

```bash
e: /Users/axelhertzberg/kandidatarbete/Digital-Journal/androidApp/src/main/java/com/EENX15_22_17/digital_journal/android/AppNavigation.kt: (109, 13): Overload resolution ambiguity: 
public fun LandingPage(visitId: String, showOverview: (patientId: String) -> Unit = ..., navToArrival: () -> Unit = ..., navToHazard: () -> Unit = ..., navToContactReason: () -> Unit = ..., navToPreviousCare: () -> Unit = ..., navToHealthHistory: () -> Unit = ..., navToHealthNow: () -> Unit = ..., navToSuicideAssessment: () -> Unit = ..., navToNursingNeed: () -> Unit = ..., navToMedicalOrder: () -> Unit = ..., navToInterimJournal: () -> Unit = ...): Unit defined in com.EENX15_22_17.digital_journal.android.ui.landingpage in file LandingPage.kt
public fun LandingPage(visitId: String, showOverview: (patientId: String) -> Unit = ..., navToArrival: () -> Unit = ..., navToHazard: () -> Unit = ..., navToContactReason: () -> Unit = ..., navToPreviousCare: () -> Unit = ..., navToHealthHistory: () -> Unit = ..., navToHealthNow: () -> Unit = ..., navToSuicideAssessment: () -> Unit = ..., navToNursingNeed: () -> Unit = ..., navToMedicalOrder: () -> Unit = ..., navToInterimJournal: () -> Unit = ...): Unit defined in com.EENX15_22_17.digital_journal.android.ui.landingpage in file landingPage.kt
```

**Comment by rickardlantz** [comment]
> Should our screens be contained in a separate package? If so I think this looks good and we should refactor the other screens to also be in the same package!
I'm not 100% sure, but I found it difficult to figure out the "hierarchy" of the screens, so I thought that representing that through packages might work.

**Review by axelhertzberg — APPROVED** [review]
Looks good and working to run after ```gradle clean``` .

**Review by erikbengtssonchalmers — APPROVED** [review]
Looks really good!

**Pull request merged**
